POST http://localhost:3003/api/blogs 
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hcmlhIiwiaWQiOiI2NWQ1ZGZiMjc0MGVhZWQ4NDdmZTRkNzUiLCJpYXQiOjE3MDg5MzQxMjgsImV4cCI6MTcwODkzNzcyOH0.kDkfz8VyPRpJX_KMwa1WQyyiOQ7nbNthoeJx7I6U68o

{
"title": "TOIIIIIIIII",
 "author": "Mia",
  "url": "testing.com", 
  "likes": 100,
  "userId": "65d5dfb2740eaed847fe4d75"
}