POST http://localhost:3003/api/blogs 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1hcmlhIiwiaWQiOiI2NWQ1ZGZiMjc0MGVhZWQ4NDdmZTRkNzUiLCJpYXQiOjE3MDkxMTUxMjEsImV4cCI6MTcwOTExODcyMX0.9NPFZ7WM2Y8zV0glNOnWXuUeu9URc3UjhqVHvld5Eyo

{
"title": "Best CSS tricks",
 "author": "Mia",
  "url": "testing.com", 
  "likes": 100,
  "userId": "65d5dfb2740eaed847fe4d75"
}