POST http://localhost:3003/api/blogs 
Content-Type: application/json

{
    "title": "Testing3",
    "author":"Katri",
    "url": "www.mypost.fi",
    "likes": 10,
    "user_id":"65cf39aa609c4181b0f95171"
}