PUT http://localhost:3003/api/blogs/65df06ff80153aaf87d8d0e3
Content-Type: application/json

{
  "title": "Must learn CSS tricks",
  "author": "Sonia",
  "url": "testingupdate.com",
  "likes": 50,
  "user": "65d5dfb2740eaed847fe4d75"
}